### ISSUE TITLE
Authenticated Git URLs fail

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/RemoteSpiNNaker#20]
Using an Authenticated git url e.g. one with a username and password in the URL directly appears to fail.

**Comment by maharjun** [comment]
As an example for this case, one may run the following.

In the HBP Portal create a New Job from repository with the following url

`https://SpiNNakerTestRepo:5LGJr%2198c6mdfa7%25@git.tugraz.at/ci/SpiNNakerTestRepo.git`

and the following command

`sample_code.py`

This results in the following error:

```
Error:
java.lang.Exception: The job type was recognised by at least one factory, but could not be decoded.  The errors are as follows:
ZipPyNNJobParametersFactory:
uk.ac.manchester.cs.spinnaker.job_parameters.JobParametersFactoryException: Error in communication or extraction
	at uk.ac.manchester.cs.spinnaker.job_parameters.ZipPyNNJobParametersFactory.getJobParameters(ZipPyNNJobParametersFactory.java:52)
	at uk.ac.manchester.cs.spinnaker.job_parameters.JobParametersFactory.getJobParameters(JobParametersFactory.java:52)
	at uk.ac.manchester.cs.spinnaker.jobprocessmanager.JobProcessManager.getJobParameters(JobProcessManager.java:267)
	at uk.ac.manchester.cs.spinnaker.jobprocessmanager.JobProcessManager.runJob(JobProcessManager.java:141)
	at uk.ac.manchester.cs.spinnaker.jobprocessmanager.JobProcessManager.main(JobProcessManager.java:235)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://SpiNNakerTestRepo:5LGJr%2198c6mdfa7%25@git.tugraz.at/ci/SpiNNakerTestRepo.git
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at uk.ac.manchester.cs.spinnaker.utils.FileDownloader.downloadFile(FileDownloader.java:75)
	at uk.ac.manchester.cs.spinnaker.job_parameters.ZipPyNNJobParametersFactory.constructParameters(ZipPyNNJobParametersFactory.java:108)
	at uk.ac.manchester.cs.spinnaker.job_parameters.ZipPyNNJobParametersFactory.getJobParameters(ZipPyNNJobParametersFactory.java:49)
	... 4 more
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://SpiNNakerTestRepo:5LGJr%2198c6mdfa7%25@git.tugraz.at/ci/SpiNNakerTestRepo.git
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2943)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:291)
	at uk.ac.manchester.cs.spinnaker.utils.FileDownloader.getTargetFile(FileDownloader.java:127)
	at uk.ac.manchester.cs.spinnaker.utils.FileDownloader.downloadFile(FileDownloader.java:71)
	... 6 more

GitPyNNJobParametersFactory:
uk.ac.manchester.cs.spinnaker.job_parameters.JobParametersFactoryException: Transport failed
	at uk.ac.manchester.cs.spinnaker.job_parameters.GitPyNNJobParametersFactory.getJobParameters(GitPyNNJobParametersFactory.java:39)
	at uk.ac.manchester.cs.spinnaker.job_parameters.JobParametersFactory.getJobParameters(JobParametersFactory.java:52)
	at uk.ac.manchester.cs.spinnaker.jobprocessmanager.JobProcessManager.getJobParameters(JobProcessManager.java:267)
	at uk.ac.manchester.cs.spinnaker.jobprocessmanager.JobProcessManager.runJob(JobProcessManager.java:141)
	at uk.ac.manchester.cs.spinnaker.jobprocessmanager.JobProcessManager.main(JobProcessManager.java:235)
Caused by: org.eclipse.jgit.api.errors.TransportException: https://SpiNNakerTestRepo@git.tugraz.at/ci/SpiNNakerTestRepo.git: not authorized
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:178)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:125)
	at uk.ac.manchester.cs.spinnaker.job_parameters.GitPyNNJobParametersFactory.constructParameters(GitPyNNJobParametersFactory.java:56)
	at uk.ac.manchester.cs.spinnaker.job_parameters.GitPyNNJobParametersFactory.getJobParameters(GitPyNNJobParametersFactory.java:35)
	... 4 more
Caused by: org.eclipse.jgit.errors.TransportException: https://SpiNNakerTestRepo@git.tugraz.at/ci/SpiNNakerTestRepo.git: not authorized
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:507)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:312)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1115)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 8 more


	at uk.ac.manchester.cs.spinnaker.jobprocessmanager.JobProcessManager.getJobParameters(JobProcessManager.java:271)
	at uk.ac.manchester.cs.spinnaker.jobprocessmanager.JobProcessManager.runJob(JobProcessManager.java:141)
	at uk.ac.manchester.cs.spinnaker.jobprocessmanager.JobProcessManager.main(JobProcessManager.java:235)
```
Note that locally, `git clone https://SpiNNakerTestRepo:5LGJr%2198c6mdfa7%25@git.tugraz.at/ci/SpiNNakerTestRepo.git` works perfectly.
